

export const GOT_CURRENT_USER_SUCC = 'GOT_CURRENT_USER_SUCC';
export const GOT_CURRENT_USER_FAIL = 'GOT_CURRENT_USER_FAIL';
export const GOT_CURRENT_USER_STATS= 'GOT_CURRENT_USER_STATS';
export const GOT_CURRENT_TOKEN = 'GOT_CURRENT_TOKEN';
export const USER_LOGOUT = 'USER_LOGOUT';